[phases.setup]
nixPkgs = ["nodejs_20", "python311", "python311Packages.pip", "ffmpeg"]

[phases.install]
cmds = [
  "npm ci",
  "pip install -U yt-dlp bgutil-ytdlp-pot-provider --break-system-packages"
]

[start]
cmd = "node index.js"
